import Footer from "@/components/shared/Footer";
import { Navbar } from "@/components/shared/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className="flex flex-col 2xl:space-y-32"
      >
        <Navbar />
        {children}
        <Footer />
      </div>
  );
}
