import type { Metadata } from "next";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Kodchasan } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";

const kodchasan = Kodchasan({ 
  subsets: ["latin"], 
  weight: ["200","300", "400", "500", "600", "700"]
});


export const metadata: Metadata = {
  title: {
    template: "%s | DAWF",
    default: "DAWF",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      variables: {
        colorBackground: "#10a07514",
        colorPrimary: '#D23D0E',
        colorText: '#fff'
        
        
      },
      elements: {
        socialButtonsBlockButton:{
          backgroundColor: '#fff'
        }
      },
      layout: {
        socialButtonsPlacement: 'bottom',
        
        // socialButtonsVariant: 'iconButton',
        // termsPageUrl: 'https://clerk.com/terms'
      }
      
    }}>
    <html lang="en">
      <body
        className={`${kodchasan.className} antialiased bg-bg-img bg-cover bg-black object-cover bg-center bg-blend-luminosity bg-no-repeat`}
      >
        <div className="bg-zinc-950/80 min-h-screen">
          
          {children}

         
        </div>
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
